### ISSUE TITLE
Can´t change from day to week view

### ISSUE THREAD

**Issue by Gatienzo** [cognophile/Deskcal#18]
Hi. Is there a way to change from day to week view? The button on the top right doesn´t work. Thanks
Windows 10
Edit: also, there is no way to log out, theaccount button at top right does not work. all butons in the top bar do not work: search, day, etc.

**Comment by cognophile** [comment]
This issue should be addressed in the latest release, [`v1.0.6`](https://github.com/cognophile/Deskcal/releases/tag/v1.0.6). Closing this issue ass resolved, but feel free to reopen/open another if you run into other problems or have suggestions.
